---
- name: Deploy Apache Web Servers on VM1 and VM2
  hosts: webservers
  become: yes
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Configure Apache to listen on port 8080
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen 80$'
        line: 'Listen 8080'

    - name: Update VirtualHost configuration for port 8080
      copy:
        dest: /etc/apache2/sites-available/000-default.conf
        content: |
          <VirtualHost *:8080>
              DocumentRoot /var/www/html
              ErrorLog ${APACHE_LOG_DIR}/error.log
              CustomLog ${APACHE_LOG_DIR}/access.log combined
          </VirtualHost>

    - name: Create custom index.html file
      copy:
        dest: /var/www/html/index.html
        content: |
          Hello World from SJSU-{{ inventory_hostname[-1] }}
      notify:
        - Restart Apache

    - name: Enable Apache service on boot and start it
      service:
        name: apache2
        enabled: yes
        state: started

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
